version: '3'

services:
  app:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 27017
      DB_NAME: ecommerce
  db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ecommerce
